# ********************************************************************************
#  Copyright (c) 2025 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

# Config file for cargo deny
# For all options see https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "EPL-2.0",
    "MIT",
    # Unicode-3.0 is not (yet) on the Eclipse Foundation's list of approved licenses
    # however, all of its predecessors are, thus we assume that 3.0 is also ok to use
    "Unicode-3.0",
    "Zlib",
]
private = { ignore = true }

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip-tree = [
    { crate = "windows-sys", reason = "a foundational crate for many that bumps far too frequently to ever have a shared version" },
    { crate = "getrandom@0.2.15", reason = "an outdated version that is still used by some other crates we depend on" },
]

[advisories]
ignore = [
    { id = "RUSTSEC-2024-0437", reason = "protobuf 3.7.2 is about to be released and includes a fix for this issue" }
]
